spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888 #removing optional
  jpa:
    show-sql: true
    defer-datasource-initialization:  true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000
resilience4j:
  circuitbreaker:
    instances:
      default:
        failure-rate-threshold: 90 # only 90%
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      sample-bulkhead-api:
        max-concurrent-calls: 10